apiVersion: v1
kind: Service
metadata:
  name: bookclub-service
  labels:
    app: bookclub
    owner: bookclub
spec:
  type: NodePort
  selector:
    app: bookclub
    tier: web
  ports:
  - port: 4000
    targetPort: 4000
